### ISSUE TITLE
Supprimer la partie du site "les organisateurs"

### ISSUE THREAD

**Issue by MoOx** [francejs/ToulouseJS#10]
Plutôt que de garder cette partie pas forcément pertinente, il faudrait plutôt mettre un tout petit mot en dessous de chaque édition pour dire `Organisé par [nom] (avec lien)`

**Comment by Atinux** [comment]
:+1:

**Comment by MoOx** [comment]
@maxdow n'hésite pas à le faire, cette partie est complètement à la rue.

**Comment by maxdow** [comment]
yep, faut vraiment que je prenne le temps d'actualiser le site..
