### ISSUE TITLE
Point veille toulousejs #8

### ISSUE THREAD

**Issue by maxdow** [francejs/ToulouseJS#14]
Ressources pour faire un petit debrief veille en début de meetup : 

React 0.14 : http://facebook.github.io/react/blog/2015/10/07/react-v0.14.html
Node 4 (4.2.1 correction faille DOS , Release LTS)
npm 3 ( perf ++ 3.3.6 ) 
Angularjs 1.5 beta 1 https://github.com/angular/angular.js/blob/master/CHANGELOG.md
spec d'Ecmascript sous github https://github.com/tc39/ecma262/releases/tag/es2016-draft-1
beta chez emberjs http://emberjs.com/blog/2015/10/04/ember-2-1-released.html
Firefox 41/42 ( source tab, screenshot DOM , perf sur restyle , HAR, debug wifi, perf flexbox , securité mode privé )

**Comment by hadrienl** [comment]
Hey y'a déjà ton blog :p

**Comment by maxdow** [comment]
ahah tout le monde ne le lit pas ( encore ;) )

**Comment by maxdow** [comment]
surtout il n'est pas exhaustif ( d'ou le billet, pour pouvoir en rajouter )
