### ISSUE TITLE
Revoir le site

### ISSUE THREAD

**Issue by maxdow** [francejs/ToulouseJS#19]
Réfléchir pour quelque chose de plus simple, plus propre.

**Comment by Torlus** [comment]
Jekyll / GitHub pages?

**Comment by MoOx** [comment]
Ruby, pour ToulouseJS ça fait tâche ^^

Sinon pour rester dans du JS, je pose ça là https://github.com/MoOx/statinamic :)
On pourrait très facilement gérer la home avec une liste de .md (un .md -> un event, le tout sur la home page). Mon moteur à plein d'avantage par rapport à des générateurs classiques. On a tous l'écosysteme node/npm/react accessible, avec du code universel.

A la limite je pourrais même m'occuper de setup tout ça, ça me permettrait de revoir ma doc :)

**Comment by hadrienl** [comment]
[Ghost](https://ghost.org/), nodeJS, associatif, open source, libre. [Exemple](https://blog.hadrien.eu/)

**Comment by maxdow** [comment]
Perso pas d'à priori. Jekyll semble dans l'air du temps mais pour avoir testé le système (avant la V3 il me semble ) le setup était lourd.

Il faut un truc le plus simple possible, tant d'un point de vue design que mise en place/ update. Pourquoi ? sinon ce sera pas mis à jour ;)

La plupart des générateurs statiques vont fournir plus ou moins quelque chose de similaire, c'est le déploiement et les possibilités qui changent .  

Après le truc c'est que vous êtes direct parti sur des solutions techniques . **C'est presque un détail**. Ce qui compte le plus c'est savoir ce qu'on met , ensuite comment on le met. Le choix de l'outil vient à la fin suivant le besoin ( et l'envie de faire les hipsters :p )

**Comment by Inateno** [comment]
J'utilise Ghost pour du blog perso, ça marche très bien, setup facile. donc +1 pour Ghost ;)

**Comment by hadrienl** [comment]
Ce qu'on met : les dates des events avant qu'ils ne se produisent :p

**Comment by Inateno** [comment]
Pour le site suffit de faire une page "A propos" on explique le principe du meetup.
Et une main page avec une cover et la liste des "articles" en dessous.

On poste un article quand un event est organisé et c'est tout nan ?

**Comment by hadrienl** [comment]
* Les vidéos des confs (qu'il faudra donc filmer)
* des articles de contributeurs libres toulousains en rapport avec js

**Comment by maxdow** [comment]
Il ne me semble pas qu'on ait le besoin de blogger ? Même si les nouveaux events peuvent s'assimiler à un article de blog c'est à voir . Y a t'il plus simple ? ( question ouverte, c'est simple sinon un post)

**Comment by Inateno** [comment]
Ben quand je dis "blogger" c'est parce que je trouve que c'est le plus simple et l'install de Ghost prend quelques minutes.

Et l'avantage c'est que si on veut y mettre autre chose/ajouter des catégories, c'est simple.

**Comment by maxdow** [comment]
Qui dit nodejs dit serveur non ?

**Comment by hadrienl** [comment]
Tu veux qu'on se cotise pour payer les 3€/mois d'une VM ?

**Comment by MoOx** [comment]
nodejs, ghost, ça part sur plus compliqué que ça ne l'est aujourdhui...

Il me semble aussi que ça part sur trop compliqué.

La page des apéroweb toulousain me semble très bien déjà http://toulouse.aperoweb.fr/.

Mon message (même si orienté technique) veut rester dans l'idée d'un truc simple, avec une finalité proche de la page énoncée si dessus.

**Comment by Inateno** [comment]
J'ai 2 dédiés sinon (je donnes pas d'accès dessus par contre donc faut que je l'installe et que je push sur le ftp).
Mais après on peut faire des comptes editeur comme on veut donc simple pour l'admin, c'est juste pour les modifs templates ou maj qu'il faudra passer par moi.

Je propose hein, ça évite de payer en plus et c'est pas pour le "peu" de traffic qui y'a que je vais voir la diff (me semble)..

**Comment by maxdow** [comment]
C'est pas tant le coût, il y a aussi une maintenance. Même si c'est néant une fois en place, la question se pose. Si on peut faire sans c'est mieux je pense. 
Pour l'usage , les solutions proposées par les générateurs statiques me semble adaptés. 
Dans un premier temps avant d'ajouter des features, le but ultime serait un site efficace, référencé et à jour oui ;)

**Comment by Inateno** [comment]
@MoOx  moi j'aime bien ton générateur ^^ le seul truc c'est qu'il faut passer par le ftp ou alors un github avec un hook qui up ça tout seul ?

**Comment by maxdow** [comment]
> J'ai 2 dédiés sinon (je donnes pas d'accès dessus par contre donc faut que je l'installe et que je push sur le ftp).
Mais après on peut faire des comptes editeur comme on veut donc simple pour l'admin, c'est juste pour les modifs templates ou maj qu'il faudra passer par moi.



C'est déja trop compliqué :p

**Comment by MoOx** [comment]
Vous êtes vraiment sérieux à penser simplifier le truc avec un serveur, une vm, ghost, des comptes editeurs... ?!

**Comment by maxdow** [comment]
[troll]e pense que l'idéal serait d'utiliser Docker Swarm pour gérer les machines[troll]

**Comment by MoOx** [comment]
@Inateno ça se plus sur gh-pages en 2min montre en main.

On a besoin de rien de plus que ce repo, une commande "npm start" pour prévisualiser et "npm build" pour générer (et encore ça sera fait par travis dans l'idéal).

Faut se focaliser sur le workflow, c'est pour ca que je propose: un markdown par event, une home qui loop sur la collection et fait un beau truc simple avec tous les events, le futur et/ou dernier étant mis en avant. On pourrait même gérer du code client pour pointer vers le bon endroit (twitter?) en cas ou les dates affichés sont passés (pour récupérer des infos à jour).

**Comment by Inateno** [comment]
@MoOx ouai ba c'est très bien (selon moi pas besoin de plus).

**Comment by Torlus** [comment]
Jekyll fait ça :)
Pages/posts en markdown, "Jekyll serve" pour le reload.
On s'en cogne à mon avis que ce soir du Ruby ou autre, de toute façon à la fin, les pages sont statiques.

**Comment by maxdow** [comment]
Merci @MoOx :)
J'ai peu de connaissances/retour sur les différents générateurs statiques. Je n'ai pas testé le tien mais je connais les technos . Cela reste subjectif donc mais je suis partant, puis ça te fait un use-case de plus et un peu de pub ;) 

Ensuite je sais que tu as une **problématique DX** et c'est ce qu'il me semble le plus important pour une refonte.

Avec un template propre, md est bien adapté.
La solution github page parait une évidence ( il y a les solutions de build pas de soucis )

**Comment by maxdow** [comment]
Petite expression de besoin sur le coin d'une table : 

Pour ajouter un event il faut un seul point d'entré ou indiquer : titre event, date , programme, lieu inscription.
Un programme c'est n fois titre de la prez et orateur.

Option pour des images : l'avatar du/des présentateur et une image pour le "thème" de la soirée si il y a ( ça peut donner de la couleur et du contenu )

Le prochain évent est mis en avant sur la home. Un accès aux anciens sur une autre page.

La gestion de la "validité" par la date est un plus. Dès que l'event est passé, il n'y a rien à faire, tant qu'il n'y a pas de prochain évent prévu, le site affiche un contenu "pas de prochain event prévu"

**Comment by maxdow** [comment]
nom de domaine alternatif possible : toulouse.js.org 
https://github.com/js-org/dns.js.org/tree/master

**Comment by MoOx** [comment]
Super idée (francejs étant ce que c'est - cad du vent).

**Comment by enguerran** [comment]
KISS : tu gères les events sur github, le site reste sur github. Tu veux pas t'embêter avec un workflow manuel, tu utilises le [générateur automatique de github-pages](https://help.github.com/articles/creating-pages-with-the-automatic-generator/). Il est basé sur jekyll, tu utilises jekyll. Tant que tu hackes pas l'outil, c'est pas grave si c'est pas du JS, amha.

![](https://help.github.com/assets/images/help/pages/page-generator-picker.png)

Pour le contenu :

- une page statique about
- une page ou un ensemble de pages incrémentales pour les events

Pour le contenu riche, passer par des services :

- hoster une vidéo : youtube ou quesaisje
- hoster des slides : slides.com, speakerdesk.com ou autre
- etc.

**Comment by MoOx** [comment]
Je vais donc attaquer ça avec Phenomic, et ça fera l'objet d'un sujet pour le tjs 13 :)
