### ISSUE TITLE
Impossible de s'inviter dans slack

### ISSUE THREAD

**Issue by Farkal** [francejs/ToulouseJS#29]
Le lien suivant [https://ct-slack-invite.herokuapp.com/](https://ct-slack-invite.herokuapp.com/) ne fonctionne plus donc il n'est plus possible de rejoindre la comunauté slack.

**Comment by MoOx** [comment]
Apparement maintenant c'est via http://communautes-toulouse.herokuapp.com/. Merci du retour.
