### ISSUE TITLE
Refaire un logo.

### ISSUE THREAD

**Issue by MoOx** [francejs/ToulouseJS#4]

**Comment by MoOx** [comment]
Je trouve que le logo n'est pas terrible, voici quelques tests basé sur le logo classique JS. (Utilisez les réactions github pour manifester de l'interet sur tel ou tel version).

**Comment by MoOx** [comment]
![simple-rose](https://cloud.githubusercontent.com/assets/157534/17807991/b5a34448-660d-11e6-9ed0-0dcba1882694.png)

**Comment by MoOx** [comment]
![rose-plus-clair](https://cloud.githubusercontent.com/assets/157534/17807995/bcd5cc36-660d-11e6-9ed2-913cf88d93a2.png)

**Comment by MoOx** [comment]
![ville-rose](https://cloud.githubusercontent.com/assets/157534/17807999/c30d5970-660d-11e6-80b5-b0376175a5ec.png)

**Comment by MoOx** [comment]
![ville-rose-alt](https://cloud.githubusercontent.com/assets/157534/17808006/d014b69a-660d-11e6-87ff-af0e3eeebff9.png)

**Comment by MoOx** [comment]
![ville-rose-alt2](https://cloud.githubusercontent.com/assets/157534/17808015/dbb4cdb4-660d-11e6-9258-eea91c4d0e80.png)

**Comment by MoOx** [comment]
![ville-rose-alt3](https://cloud.githubusercontent.com/assets/157534/17808023/e83f3600-660d-11e6-9e05-d46a4f3bc23e.png)

**Comment by MoOx** [comment]
![ville-rose-alt4](https://cloud.githubusercontent.com/assets/157534/17808035/f2a2baea-660d-11e6-9b0f-1f97ef2718ac.png)

**Comment by maxdow** [comment]
Je ne suis pas forcément fan du rose, peut être un peu trop pêchu. Sur le site toulouse.fr ils utilisent du #bc127f. A voir

**Comment by MoOx** [comment]
![rose-fonce](https://cloud.githubusercontent.com/assets/157534/17809227/63b46376-6615-11e6-9de0-0b2ec3a0ab90.png)

**Comment by MoOx** [comment]
Pour le coup c'est un peu foncé

**Comment by maxdow** [comment]
Pas sur que ce concept aboutisse enfait ça fait très jsconfEU :p http://2014.jsconf.eu/

**Comment by arcanis** [comment]
![image](https://cloud.githubusercontent.com/assets/1037931/17809398/964543ea-6616-11e6-8039-4e70b1cbbcef.png)

**Comment by goldoraf** [comment]
Plutôt partant pour la croix d'Occitanie, en plus gros et derrière les lettres ce serait encore mieux. @MoOx : pour un logo, l'utilisation d'une photo est contre indiquée, ça ne donnera rien avec des dimensions réduites.

**Comment by maxdow** [comment]
@goldoraf @arcanis .. et d'une opacité + faible :)

**Comment by MoOx** [comment]
Faut penser au couleur du site aussi. En jaune ça va faire babeljs... :)

**Comment by arcanis** [comment]
Autre proto:

![image](https://cloud.githubusercontent.com/assets/1037931/17809742/fcdf648a-6618-11e6-88b1-2886a6a62ca0.png)

**Comment by arcanis** [comment]
Autre proto:

![image](https://cloud.githubusercontent.com/assets/1037931/17809780/258eef72-6619-11e6-9781-59bf33e28b8e.png)

Oui, j'ai réutilisé le logo standard de javascript (donc jaune et noir), mais la couleur peut être différente.

**Comment by goldoraf** [comment]
@MoOx tu n'as pas tort, et d'ailleurs un rouge brique serait bien (parce que bon, ville rose mon c..., la brique c'est rouge brique, pas rose)

**Comment by MoOx** [comment]
J'ai fais des tests de mon  côté avec la croix en fond (centrée), c'est pas top du tout donc je montre même pas. La première idée d' @arcanis me plait bien.

**Comment by maxdow** [comment]
+1 pour brique rouge

**Comment by MoOx** [comment]
kdo les gens

![brique](https://cloud.githubusercontent.com/assets/157534/17810029/e2f302b4-661a-11e6-9c83-833baac25ba7.png)

**Comment by arcanis** [comment]
Similaire à la première, avec un fond rouge et flat:

![image](https://cloud.githubusercontent.com/assets/1037931/17810160/c4e69e74-661b-11e6-95a5-3a8df3445b20.png)

**Comment by arcanis** [comment]
Btw, https://github.com/voodootikigod/logo.js/blob/master/registry.md

**Comment by MoOx** [comment]
Avec le text en blanc pour le coup ca serait moins violent :)

**Comment by arcanis** [comment]
![image](https://cloud.githubusercontent.com/assets/1037931/17810454/76ca588c-661d-11e6-866d-ed22dd1e6731.png)

**Comment by hadrienl** [comment]
Pique le dégradé de toulouse.fr : http://toulouse.fr/

**Comment by kncs** [comment]
Et avec la croix d'Occitanie en guise de point sur le J ?

![toulouse js](https://cloud.githubusercontent.com/assets/10996604/17816534/ecaed368-6639-11e6-8636-febf6c8f164e.png)

**Comment by MoOx** [comment]
Je vois mal comment faire un site sympa avec ces couleurs... Faut penser à ça aussi imo.

**Comment by MoOx** [comment]
Faut aussi penser au logo en petit, la croix trop petite ne se vera plus et fera paté.

**Comment by enguerran** [comment]
Et avec le carré rouge en forme de croix d'occitanie, ça donnerait pas bien ? J'ai vu plusieurs flag-JS de la sorte en forme de l'état américain qui-va-bien ou du pays en-question.

**Comment by MoOx** [comment]
@enguerran je viens de faire un test, du coup c'est difficile de placer le "JS" dedans/à cheval dessus...
Je vais poser 2 autres essais qui passent pas trop mal en petit.

**Comment by MoOx** [comment]
![rose-gradient-alt copy](https://cloud.githubusercontent.com/assets/157534/18020085/d94cb1c2-6bdf-11e6-8193-3e5de1f39d30.jpg)
![rose-gradient-alt](https://cloud.githubusercontent.com/assets/157534/18020086/d95a099e-6bdf-11e6-9a0b-b40282b0ce35.jpg)

**Comment by MoOx** [comment]
![rose-gradient copy](https://cloud.githubusercontent.com/assets/157534/18020099/f039a584-6bdf-11e6-9f24-20095e6029c8.jpg)
![rose-gradient](https://cloud.githubusercontent.com/assets/157534/18020100/f03aada8-6bdf-11e6-8975-8cff9b4a81e0.jpg)

**Comment by maxdow** [comment]
J'aime bien le JS en blanc la croix et le dégradé, mais les couleurs j'ai un doute... je pense qu'on est trop sur les tons de jsconfEU. Certes les couleurs du site de Toulouse sont comme ça :p

**Comment by enguerran** [comment]
Faut du rouge et du noir pour les couleurs, ça n'est pas trop utilisé ailleurs et ce sont des couleurs toulousaines ;)

**Comment by maxdow** [comment]
Ouais à part Debian et Jeanne Mas on est bon pour le rouge et le noir :)

Inspiration : 
![toile-tlse-r-n-3_67](https://cloud.githubusercontent.com/assets/711050/18027881/880d2ff4-6c6f-11e6-972f-3020e22b0ceb.jpg)

**Comment by kncs** [comment]
De mon coté, j'aime pas trop le rouge et le noir, c'est trop typé Stade Toulousain. Est ce que la croix occitane ne suffirait-elle pas pour l'identité toulousaine ?

**Comment by MoOx** [comment]
Rouge et noir ça fait trop stade en effet. Quand je repasse sur mon ordi je tente en rouge/jaune classique de la croix. Je pense que ça sera pas mal.

**Comment by kncs** [comment]
Je viens d'essayer avec les couleurs de l'année 2016.

![toulouse2](https://cloud.githubusercontent.com/assets/10996604/18028017/7c5f850e-6c73-11e6-9149-82598fbdf107.jpg)

**Comment by MoOx** [comment]
Quelques autres tests avoir rouge/blanc/jaune/noir pour tester un peu à partir de vos envies.

**Comment by MoOx** [comment]
![rouge-blanc-noir](https://cloud.githubusercontent.com/assets/157534/18030277/881cea8e-6cb0-11e6-8aae-f2ada12437be.jpg)

**Comment by MoOx** [comment]
![rouge-jaune-noir](https://cloud.githubusercontent.com/assets/157534/18030282/a8d545aa-6cb0-11e6-941f-eea151b547f6.jpg)

**Comment by MoOx** [comment]
![rouge-jaune](https://cloud.githubusercontent.com/assets/157534/18030284/b6d94250-6cb0-11e6-88b4-65215916166c.jpg)

**Comment by MoOx** [comment]
Variante avec la croix pleine

![rouge-jaune-plein](https://cloud.githubusercontent.com/assets/157534/18030287/c27e1022-6cb0-11e6-805c-099c1fe3c2b5.jpg)

**Comment by MoOx** [comment]
A noter que j'ai choisi un dégradé rouge, car rouge simple ça pique un peu. Le dégradé n'est peut être pas optimal ici, mais sur un header de site ça peut être discret et sympa :)

**Comment by maxdow** [comment]
Je préfère avec le JS en blanc. Le dégradé je trouve nickel. La croix, jaune plutot la version légère. Franchement c'est cool, j'aime bien l'avant dernier

**Comment by hadrienl** [comment]
Top le dernier !

**Comment by enguerran** [comment]
Pas mal de validation pour [l'avant dernier](https://github.com/francejs/ToulouseJS/issues/4#issuecomment-242942724).

> Le mieux est l'ennemi du bien

**Comment by MoOx** [comment]
Ouais. Moi je dis qu'on peut s'arrêter là dessus.

**Comment by hadrienl** [comment]
T'as pas peur que ça rende dégueulasse en petit format avec juste le contour de la croix ?

**Comment by MoOx** [comment]
Ca reste tout à fait correct.

![screen shot 2016-08-29 at 09 51 05](https://cloud.githubusercontent.com/assets/157534/18044437/26474506-6dce-11e6-9345-2e02215bb89e.png)

**Comment by hadrienl** [comment]
Cool alors !

**Comment by maxdow** [comment]
Favicon à tester

**Comment by MoOx** [comment]
Pour le coup le favicon passe mieux avec la croix pleine

![screen shot 2016-08-29 at 12 37 46](https://cloud.githubusercontent.com/assets/157534/18048936/71dc053a-6de5-11e6-86a2-c4e0cb748938.png)
![screen shot 2016-08-29 at 12 37 31](https://cloud.githubusercontent.com/assets/157534/18048943/76a09568-6de5-11e6-9c7f-f7fc21a3f5fa.png)

**Comment by enguerran** [comment]
le favicon avec la croix pleine passe peut-être mieux, mais on ne peut pas savoir que c'est une croix occitane si on ne le sait pas d'avance.

**Comment by MoOx** [comment]
Et donc tu proposes quoi?

**Comment by arcanis** [comment]
Je trouve que la croix vide rend mieux que la pleine, même en favicon (la pleine ressemble à un +, la vide laisse entrevoir l'existence d'un symbole sans pour autant le déformer).

**Comment by hadrienl** [comment]
Je suis assez d'accord avec @arcanis finalement.

**Comment by MoOx** [comment]
On pourra travailler en pixel perfect pour le favicon :) Mais ouais dans l'idée ça ira.
Curieux de savoir ce qu'en penses @goldoraf :)

**Comment by enguerran** [comment]
J'en pense comme @arcanis et les précédents votes de https://github.com/francejs/ToulouseJS/issues/4#issuecomment-242942724

**Comment by MoOx** [comment]
Je pense qu'on peut valider en effet. Je vais m'atteler à refaire le site tout bientôt et je le prendrais en compte.

**Comment by MoOx** [comment]
Le logo est dans le repo en sketch et svg.
