### ISSUE TITLE
Track publish warning

### ISSUE THREAD

**Issue by MoOx** [francejs/ToulouseJS#9]
https://github.com/francejs/francejs.github.com/issues/112

**Comment by MoOx** [comment]
Je vais bumper car je reçois "plein" de mail et ça commence à me gonfler gentillement :)

**Comment by MoOx** [comment]
Si y'a rien qui avance dans ce sens, on devrait réfléchir à changer de nom de domaine...

**Comment by maxdow** [comment]
ah oui je pensais que c'était résolu :/

2016-01-18 15:43 GMT+01:00 Maxime Thirouin <notifications@github.com>:

> Si y'a rien qui avance dans ce sens, on devrait réfléchir à changer de nom
> de domaine...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/francejs/ToulouseJS/issues/9#issuecomment-172546574>.
>



-- 
Maxime WARNIER

**Comment by enguerran** [comment]
Je bumpe l'issue pour la clore le cas échéant. J'ai vu sur francejs/francejs.github.com#112 que des trucs avaient été fait. Tu reçois encore des warnings @MoOx ?

**Comment by MoOx** [comment]
Non mais je sais pas si il y a eu bcp de maj...

**Comment by MoOx** [comment]
Ca à l'air bon, pas de warnings depuis la dernière maj.
